"""
Export service for generating various output formats from architecture analysis
"""
import json
from typing import List, Dict, Any
from app.models.analysis import AnalysisResult, MicroserviceSchema, DependencyInfo


class ArchitectureExporter:
    """Export architecture analysis to various formats"""
    
    @staticmethod
    def to_markdown(analysis: AnalysisResult) -> str:
        """Generate comprehensive Markdown documentation"""
        
        md = f"""# Microservice Architecture Design
**Project:** {analysis.project_id}  
**Source:** {analysis.raw_filename}  
**Generated by:** ArchAItect AI

---

## 📊 Architecture Overview

This document describes the recommended microservice architecture extracted from requirements analysis.

### Architecture Quality Metrics

| Metric | Score | Assessment |
|--------|-------|------------|
| 🚀 Scalability | {analysis.metrics.scalability}/100 | {ArchitectureExporter._get_assessment(analysis.metrics.scalability)} |
| 🔗 Coupling | {analysis.metrics.coupling}/100 | {ArchitectureExporter._get_coupling_assessment(analysis.metrics.coupling)} |
| 🛡️ Fault Isolation | {analysis.metrics.fault_isolation}/100 | {ArchitectureExporter._get_assessment(analysis.metrics.fault_isolation)} |

### Summary Statistics

- **Total Microservices:** {len(analysis.microservices)}
- **Total Dependencies:** {len(analysis.dependencies)}
- **Sync Dependencies:** {sum(1 for d in analysis.dependencies if d.type == 'sync')}
- **Async Dependencies:** {sum(1 for d in analysis.dependencies if d.type == 'async')}

---

## 🏗️ Microservices Catalog

"""
        
        # Document each microservice
        for i, service in enumerate(analysis.microservices, 1):
            md += f"""### {i}. {service.name}

**ID:** `{service.id}`  
**Domain:** {service.domain}  
**Database:** {service.database}

#### Description
{service.description}

#### Database Rationale
{service.database_reasoning}

#### API Endpoints

"""
            # Document APIs
            for api in service.apis:
                md += f"- **{api.method}** `{api.path}`  \n  {api.description}\n\n"
                
            # Scaling recommendations
            md += "#### Scaling & Architecture Recommendations\n\n"
            for rec in service.scaling_recommendations:
                md += f"- {rec}\n"
            
            md += "\n---\n\n"
        
        # Document dependencies
        md += """## 🔗 Service Dependencies

The following diagram shows how services interact with each other:

"""
        
        for dep in analysis.dependencies:
            sync_icon = "🔄" if dep.type == "sync" else "📨"
            md += f"- {sync_icon} **{dep.source}** → **{dep.target}** (`{dep.type}`)\n  _{dep.description}_\n\n"
        
        # Add Mermaid diagram
        md += "\n## 📈 Architecture Diagram (Mermaid)\n\n```mermaid\n"
        md += ArchitectureExporter.to_mermaid(analysis)
        md += "\n```\n\n"
        
        return md
    
    @staticmethod
    def _get_assessment(score: int) -> str:
        """Get text assessment for a score"""
        if score >= 80:
            return "Excellent ✅"
        elif score >= 60:
            return "Good 👍"
        elif score >= 40:
            return "Moderate ⚠️"
        else:
            return "Needs Improvement ⚠️"
    
    @staticmethod
    def _get_coupling_assessment(score: int) -> str:
        """Get coupling assessment (lower is better)"""
        if score <= 30:
            return "Low Coupling ✅"
        elif score <= 50:
            return "Moderate Coupling 👍"
        elif score <= 70:
            return "High Coupling ⚠️"
        else:
            return "Very High Coupling ❌"
    
    @staticmethod
    def to_mermaid(analysis: AnalysisResult) -> str:
        """Generate Mermaid diagram code"""
        
        mermaid = "graph TD\n"
        
        # Define service nodes
        for service in analysis.microservices:
            # Sanitize IDs for Mermaid
            node_id = service.id.replace("-", "_")
            label = service.name.replace("Service", "Svc")
            mermaid += f"    {node_id}[\"{label}<br/>{service.database}\"]\n"
        
        mermaid += "\n"
        
        # Define dependencies
        for dep in analysis.dependencies:
            source_id = dep.source.replace("-", "_")
            target_id = dep.target.replace("-", "_")
            
            if dep.type == "async":
                mermaid += f"    {source_id} -.->|async| {target_id}\n"
            else:
                mermaid += f"    {source_id} -->|sync| {target_id}\n"
        
        # Add styling
        mermaid += "\n    classDef serviceNode fill:#1e40af,stroke:#3b82f6,stroke-width:2px,color:#fff\n"
        mermaid += "    class " + ",".join(s.id.replace("-", "_") for s in analysis.microservices) + " serviceNode\n"
        
        return mermaid
    
    @staticmethod
    def to_plantuml(analysis: AnalysisResult) -> str:
        """Generate PlantUML component diagram"""
        
        puml = "@startuml\n"
        puml += "!theme plain\n"
        puml += "skinparam componentStyle rectangle\n"
        puml += "skinparam backgroundColor #0f172a\n"
        puml += "skinparam componentBackgroundColor #1e293b\n"
        puml += "skinparam componentBorderColor #3b82f6\n"
        puml += "skinparam ArrowColor #60a5fa\n\n"
        
        puml += "title Microservice Architecture\\n\\n\n\n"
        
        # Define components
        for service in analysis.microservices:
            db_icon = "database" if "SQL" in service.database or "Postgres" in service.database else "storage"
            puml += f"component \"{service.name}\" as {service.id.replace('-', '_')} #1e40af\n"
            puml += f"database \"{service.database}\" as db_{service.id.replace('-', '_')}\n"
            puml += f"{service.id.replace('-', '_')} --> db_{service.id.replace('-', '_')}\n\n"
        
        # Define dependencies
        for dep in analysis.dependencies:
            source = dep.source.replace("-", "_")
            target = dep.target.replace("-", "_")
            
            if dep.type == "async":
                puml += f"{source} ..> {target} : async\n"
            else:
                puml += f"{source} --> {target} : sync\n"
        
        puml += "\n@enduml"
        return puml
    
    @staticmethod
    def to_json_schema(analysis: AnalysisResult) -> Dict[str, Any]:
        """Export as structured JSON schema for tools/CI/CD"""
        
        return {
            "schema_version": "1.0",
            "project_id": analysis.project_id,
            "source_document": analysis.raw_filename,
            "timestamp": "auto",
            "services": [
                {
                    "id": svc.id,
                    "name": svc.name,
                    "description": svc.description,
                    "domain": svc.domain,
                    "persistence": {
                        "type": svc.database,
                        "reasoning": svc.database_reasoning
                    },
                    "apis": [
                        {
                            "path": api.path,
                            "method": api.method,
                            "description": api.description
                        }
                        for api in svc.apis
                    ],
                    "scaling": svc.scaling_recommendations,
                    "metadata": svc.metadata
                }
                for svc in analysis.microservices
            ],
            "dependencies": [
                {
                    "from": dep.source,
                    "to": dep.target,
                    "type": dep.type,
                    "description": dep.description
                }
                for dep in analysis.dependencies
            ],
            "quality_metrics": {
                "scalability": analysis.metrics.scalability,
                "coupling": analysis.metrics.coupling,
                "maintainability": analysis.metrics.maintainability,
                "fault_isolation": analysis.metrics.fault_isolation
            },
            "analysis_metadata": analysis.analysis_metadata
        }
    
    @staticmethod
    def to_openapi_stub(service: MicroserviceSchema) -> Dict[str, Any]:
        """Generate OpenAPI 3.0 spec stub for a service"""
        
        spec = {
            "openapi": "3.0.0",
            "info": {
                "title": service.name,
                "description": service.description,
                "version": "1.0.0"
            },
            "servers": [
                {
                    "url": "http://localhost:8000",
                    "description": "Development server"
                }
            ],
            "paths": {}
        }
        
        # Generate path definitions
        for api in service.apis:
            if api.path not in spec["paths"]:
                spec["paths"][api.path] = {}
            
            method_lower = api.method.lower()
            spec["paths"][api.path][method_lower] = {
                "summary": api.description,
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        
        return spec
